/**
 * The Idea Generator — the caller `buildIdeaGeneratorPrompt` never had.
 *
 * ## What was broken
 *
 * `ideas` is the entry point of the entire generation pipeline: `generate.ts`
 * reads `status = 'proposed'`, scores them with `scoreIdeas`, selects with
 * `selectIdeas`, and drafts. All of that is built and tested.
 *
 * Its **only writer in the repository was `supabase/seed-demo.sql`.** Not a
 * handler, not a route, not a server action — a demo seed. So `generate` ran on
 * its schedule, found nothing proposed, logged "no proposed ideas to draft" and
 * returned. Every day. The agent registry has said so plainly all along:
 * "Only the prompt builder exists. There is no agent function that sends it, and
 * nothing calls the builder — not even a test. Ideas are currently scored but
 * never generated by a model."
 *
 * Separately, `signals` — written by `collect_watch_terms` when a question
 * recurs — was read by **nothing**. Two adjacent breaks: observations could not
 * become ideas, and ideas could not exist at all.
 *
 * ## Why a model here, and not deterministic promotion
 *
 * Turning "this question was asked nine times" into "here is an angle worth
 * writing" is *writing*, which is the half the governing rule assigns to a
 * model. The deterministic half is everything after: `scoreIdeas` weighs mix
 * debt, novelty and cooldowns; `selectIdeas` applies hard caps; the QC gates
 * judge the draft. A template that manufactured angles would be a second,
 * competing idea pipeline — and a worse one.
 *
 * So this proposes, and nothing here decides. Proposals arrive as
 * `status = 'proposed'` and every existing gate still runs.
 *
 * ## Provenance is not optional
 *
 * `ideas.source_signals` already exists as an array column, designed for
 * exactly this. Every proposal carries the signal ids that were in front of the
 * model when it wrote, so an idea can always answer "what made you think this".
 * A proposal that cites nothing is still recorded — the mix state and the
 * product brief are real inputs too — but it says so rather than borrowing
 * credit from a signal it did not use.
 */
import { buildIdeaGeneratorPrompt } from './prompts.js';
import { STRATEGY_MODEL, asArray, asString, extractJson, type LlmClient } from './llm.js';
import { IDEA_CATEGORIES, type IdeaCategory } from './ideaEngine.js';

export interface SignalForIdeas {
  id: string;
  source: string;
  summary: string;
}

export interface IdeaProposal {
  title: string;
  angle: string;
  category: IdeaCategory;
  rationale: string;
  needsArtifact: boolean;
  suggestedFormats: string[];
  daysUntilSeasonalPeak: number | null;
  /** The signal ids that were in front of the model. Never invented. */
  sourceSignalIds: string[];
}

export interface ProposeIdeasInput {
  productBrief: string;
  voiceSummary: string;
  signals: SignalForIdeas[];
  recentTitles: string[];
  topPerformers: Array<{ title: string; category: string; activatedUsers?: number }>;
  mixTargets: Record<string, number>;
  mixActual: Record<string, number>;
  seasonalWindow: string[];
  /** How many to ask for. The scorer will discard most of them. */
  count?: number;
}

export interface ProposeIdeasResult {
  proposals: IdeaProposal[];
  /** Proposals the model returned that were dropped, and why. */
  rejected: Array<{ title: string; reason: string }>;
  promptVersion: string;
  costUsd: number;
}

/**
 * Ask for ideas, then keep only the ones that are actually usable.
 *
 * Validation is deliberate and narrow rather than schema-driven: it checks the
 * fields the pipeline goes on to *use*, which is where a malformed answer turns
 * into a broken row. A proposal with no title or no angle is not a thin idea, it
 * is an unusable one — `generate` builds its copywriter prompt from both.
 */
export async function proposeIdeas(
  input: ProposeIdeasInput,
  llm: LlmClient,
): Promise<ProposeIdeasResult> {
  const signalIds = input.signals.map((s) => s.id);

  const prompt = buildIdeaGeneratorPrompt({
    productBrief: input.productBrief,
    voiceSummary: input.voiceSummary,
    signals: input.signals.map((s) => ({ source: s.source, summary: s.summary })),
    recentTitles: input.recentTitles,
    topPerformers: input.topPerformers,
    mixTargets: input.mixTargets,
    mixActual: input.mixActual,
    seasonalWindow: input.seasonalWindow,
    count: input.count ?? 8,
  });

  const response = await llm.complete({
    system: prompt.system,
    messages: [{ role: 'user', content: prompt.user }],
    model: STRATEGY_MODEL,
    maxTokens: 2000,
    promptVersion: prompt.version,
  });

  const rejected: Array<{ title: string; reason: string }> = [];
  let parsed: unknown;
  try {
    parsed = extractJson(response.text);
  } catch (err) {
    // No retry loop here: a proposal round is cheap to skip and `generate` runs
    // again tomorrow. Recorded as a rejection so an empty result is explicable.
    return {
      proposals: [],
      rejected: [{ title: '(response)', reason: `Not valid JSON: ${(err as Error).message}` }],
      promptVersion: prompt.version,
      costUsd: response.costUsd,
    };
  }

  const raw = asArray<Record<string, unknown>>((parsed as { ideas?: unknown })?.ideas);
  const proposals: IdeaProposal[] = [];
  const seen = new Set<string>();

  for (const candidate of raw) {
    if (!candidate || typeof candidate !== 'object') {
      rejected.push({ title: '(entry)', reason: 'not an object' });
      continue;
    }
    const title = asString(candidate.title);
    const angle = asString(candidate.angle);
    if (!title) {
      rejected.push({ title: '(untitled)', reason: 'no title' });
      continue;
    }
    if (!angle) {
      // `generate` builds the copywriter prompt from the angle. Without one the
      // draft would be written from a headline, which is how slop happens.
      rejected.push({ title, reason: 'no angle' });
      continue;
    }

    const category = asString(candidate.category) ?? '';
    if (!(IDEA_CATEGORIES as readonly string[]).includes(category)) {
      // A category outside the list would fail the database check constraint on
      // insert. Rejected here, where the reason is still legible.
      rejected.push({ title, reason: `unknown category "${category}"` });
      continue;
    }

    /**
     * Within-response duplicates, which models produce readily when asked for
     * eight of something. The cross-run novelty check is `scoreIdeas`, over
     * embeddings; this is only the cheap exact case.
     */
    const key = title.toLowerCase().replace(/\s+/g, ' ').trim();
    if (seen.has(key)) {
      rejected.push({ title, reason: 'duplicate of another proposal in the same response' });
      continue;
    }
    seen.add(key);

    const days = candidate.days_until_seasonal_peak;
    proposals.push({
      title,
      angle,
      category: category as IdeaCategory,
      rationale: asString(candidate.rationale) ?? '',
      needsArtifact: candidate.needs_artifact === true,
      suggestedFormats: asArray<unknown>(candidate.suggested_formats)
        .map((f) => asString(f))
        .filter((f): f is string => f !== null),
      daysUntilSeasonalPeak: typeof days === 'number' && Number.isFinite(days) ? days : null,
      /**
       * Every signal that was in the prompt, not a subset the model claimed.
       * Asking a model which of its inputs it used produces a confident answer
       * and no evidence; what is true is that these were in front of it.
       */
      sourceSignalIds: signalIds,
    });
  }

  return { proposals, rejected, promptVersion: prompt.version, costUsd: response.costUsd };
}
