/**
 * Generated imagery, and the line it must never cross. §213.
 *
 * Halyard's video is type on a flat ground because the artifact contract had
 * nowhere to put a picture and no way to make one. Generative image and video
 * models close that — a loaf of bread, a lit kitchen, steam off a pan — and
 * they close it at the cost of the one property this system is built on.
 *
 * ## The line
 *
 * **Generated imagery may illustrate. It may never evidence.**
 *
 * A photograph of bread is atmosphere: it says "this is about baking", and it
 * is true in the way a stock photograph on an article is true. A picture of
 * *the product's screen* generated by a model is a claim about software that
 * does not look like that — the exact fabrication gotcha 9 and §2.4 of the
 * specification forbid, and worse than a text card, because a picture is
 * believed.
 *
 * So provenance is carried on every image, planners may only use `generated`
 * imagery in decorative roles, and `creativeQC` fails a piece that puts a
 * generated image where proof belongs. Three layers, because a rule this
 * important should not rest on any one of them.
 *
 * ## Why a seam rather than a provider
 *
 * The same reason `llm.ts` is a seam: the field moves, keys differ per
 * operator, and a test must never need one. `OpenAiImageClient` is the first
 * implementation because that key already exists here. A Gemini/Imagen or a
 * Veo/Runway client is a new class implementing the same interface, and
 * nothing above this file changes.
 */

/**
 * Where a picture came from, and therefore what it is allowed to say.
 *
 * `product`   — the product's own API returned it. Can evidence.
 * `captured`  — Halyard recorded the real product. Can evidence.
 * `generated` — a model made it. **Illustration only.**
 * `operator`  — a human supplied it. Can evidence; a person took responsibility.
 */
export type ImageProvenance = 'product' | 'captured' | 'generated' | 'operator';

/**
 * What Halyard is allowed to *do* with a picture, which is a separate question
 * from where it came from. §216.
 *
 * RecipeFix forced this distinction and it generalises. Its Discover catalogue
 * returns a real photograph for every recipe, and every one carries the same
 * note: *"Publisher's own og:image — attribute and link back; do not re-host or
 * present as a RecipeFix asset."* The images belong to Budget Bytes, Love and
 * Lemons and Sally's Baking Addiction.
 *
 * So provenance says `product` — RecipeFix's own API returned it, and it
 * depicts something real — while the licence says the one thing that matters
 * for social: it cannot be burned full-bleed into a branded video. Reading
 * provenance alone would have concluded the opposite.
 *
 * `owned`                — the operator or the product owns it. Any use.
 * `attribution_required` — usable only where a visible credit and a working
 *                          link back are both rendered.
 * `generated`            — a model made it. Illustration only (§213).
 */
export type ImageLicense = 'owned' | 'attribution_required' | 'generated';

export interface ImageAttribution {
  /** Who took it. Rendered on screen when the licence requires it. */
  publisher: string;
  /** Where it came from. Must be linked, not merely named. */
  sourceUrl: string;
}

/** Provenances that may back a claim about the product. */
export const EVIDENTIAL_PROVENANCE: readonly ImageProvenance[] = [
  'product',
  'captured',
  'operator',
];

export function canEvidence(provenance: ImageProvenance): boolean {
  return EVIDENTIAL_PROVENANCE.includes(provenance);
}

/**
 * Beat roles whose whole purpose is to show the product doing something.
 *
 * A generated image in any of these is the fabrication case. Named here rather
 * than inside the gate so the planner and the critic read the same list.
 */
export const EVIDENTIAL_ROLES: readonly string[] = ['demo', 'proof', 'before', 'after', 'change'];

export interface ImageRequest {
  /**
   * What to draw. Written by the caller, never by this module.
   *
   * `assertIllustrative` rejects a prompt that reaches for the product, so a
   * caller cannot accidentally ask for the thing that must not exist.
   */
  prompt: string;
  /** '9:16' | '1:1' | '16:9'. The provider maps it to its own sizes. */
  aspectRatio: string;
  /** Alt text is required at the point of request, not bolted on afterwards. */
  alt: string;
}

export interface GeneratedImage {
  /** Bytes, so the caller stores it in Halyard's own storage rather than hotlinking. */
  data: Uint8Array;
  mimeType: string;
  width: number;
  height: number;
  provenance: 'generated';
  /** The exact prompt, kept so a published frame is traceable to what asked for it. */
  prompt: string;
  alt: string;
  model: string;
  costUsd: number;
}

export interface ImageClient {
  generate(request: ImageRequest): Promise<GeneratedImage>;
}

/**
 * Words that mean the caller is asking a model to draw the product.
 *
 * Deliberately blunt and deliberately over-broad. A false positive costs one
 * rejected prompt; a false negative puts an invented screenshot of somebody's
 * software into a published video.
 */
const PRODUCT_SHAPED = [
  'screenshot', 'screen shot', 'ui', 'user interface', 'app screen', 'dashboard',
  'interface', 'mockup', 'wireframe', 'button', 'menu', 'the app', 'our app',
  'website', 'web page', 'webpage', 'browser', 'mobile app', 'product screen',
  'settings page', 'login', 'sign-up', 'signup form',
];

export class FabricationRefused extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'FabricationRefused';
  }
}

/**
 * Refuse a prompt that asks a model to draw the product.
 *
 * Called by every provider implementation before it spends anything, so the
 * refusal does not depend on which client is configured.
 */
export function assertIllustrative(prompt: string): void {
  const lowered = ` ${prompt.toLowerCase()} `;
  for (const term of PRODUCT_SHAPED) {
    if (lowered.includes(` ${term} `) || lowered.includes(`${term}s `)) {
      throw new FabricationRefused(
        `Refusing to generate "${term}". A model drawing a product's interface invents software ` +
          'that does not exist. Product imagery must come from the product or from a capture — ' +
          'see §213 and gotcha 9.',
      );
    }
  }
}

/**
 * Whether this image may back this beat.
 *
 * The planner's check. `creativeQC` repeats it against the rendered artifact,
 * because a planner is a thing that can be bypassed and a gate is not.
 */
export function imageAllowedForRole(provenance: ImageProvenance, role: string): boolean {
  if (canEvidence(provenance)) return true;
  return !EVIDENTIAL_ROLES.includes(role);
}

/** Where a picture is being drawn, which decides what its licence permits. */
export type ImageUsage =
  /** Filling the frame of a branded post. The strongest claim of ownership. */
  | 'full_bleed'
  /** Inside a frame, with a credit rendered beside it. */
  | 'attributed_inset'
  /** Not drawn at all — a link, a thumbnail in Halyard's own UI. */
  | 'reference';

export interface LicenceDecision {
  allowed: boolean;
  /** True when the composition must render a credit for this to be allowed. */
  requiresVisibleCredit: boolean;
  reason: string;
}

/**
 * May this picture be used this way?
 *
 * The rule that stops Halyard republishing someone else's photograph as its
 * own. An `attribution_required` image full-bleed under a brand wordmark is
 * exactly "re-host and present as a RecipeFix asset", whatever the intent —
 * and the intent is not the test, the rendered frame is.
 *
 * Deliberately returns a reason rather than a boolean alone: an operator who
 * sees a strong image rejected needs to know it is a licence decision and not
 * a quality one.
 */
export function licenceAllows(
  license: ImageLicense,
  usage: ImageUsage,
  attribution?: ImageAttribution | null,
): LicenceDecision {
  if (license === 'owned') {
    return { allowed: true, requiresVisibleCredit: false, reason: 'Owned; any use.' };
  }

  if (license === 'generated') {
    return {
      allowed: usage !== 'reference',
      requiresVisibleCredit: false,
      reason: 'Generated; illustration only, and never as product evidence (§213).',
    };
  }

  /* attribution_required */
  if (usage === 'full_bleed') {
    return {
      allowed: false,
      requiresVisibleCredit: true,
      reason:
        `Licensed for attribution-linked reference only${attribution ? ` (${attribution.publisher})` : ''}. ` +
        'Filling a branded frame with it re-hosts someone else\'s photograph as this account\'s own.',
    };
  }

  if (!attribution?.publisher || !attribution?.sourceUrl) {
    return {
      allowed: false,
      requiresVisibleCredit: true,
      reason: 'Attribution required, and no publisher or source URL was supplied to render.',
    };
  }

  return {
    allowed: true,
    requiresVisibleCredit: true,
    reason: `Permitted with a visible credit to ${attribution.publisher} and a link back.`,
  };
}
